@extends('layouts.admin')
@section('title','Kho thuốc') @section('pageTitle','Danh mục & tồn kho thuốc')
@section('content')
<div class="panel mb-4"><details><summary class="btn btn-primary">Thêm thuốc mới</summary>
<form method="post" action="{{ route('admin.medicines.store') }}" class="row g-3 mt-2">@csrf
<div class="col-md-3"><label class="form-label">Mã thuốc</label><input class="form-control" name="medicine_code" required></div><div class="col-md-5"><label class="form-label">Tên thuốc</label><input class="form-control" name="name" required></div><div class="col-md-4"><label class="form-label">Hoạt chất</label><input class="form-control" name="active_ingredient"></div>
<div class="col-md-3"><label class="form-label">Dạng bào chế</label><input class="form-control" name="dosage_form"></div><div class="col-md-3"><label class="form-label">Hàm lượng</label><input class="form-control" name="strength"></div><div class="col-md-2"><label class="form-label">Đơn vị</label><input class="form-control" name="unit" value="Viên"></div><div class="col-md-4"><label class="form-label">Nhà sản xuất</label><input class="form-control" name="manufacturer"></div>
<div class="col-md-3"><label class="form-label">Giá nhập</label><input class="form-control" type="number" name="purchase_price" value="0"></div><div class="col-md-3"><label class="form-label">Giá bán</label><input class="form-control" type="number" name="selling_price" required></div><div class="col-md-3"><label class="form-label">Tồn kho</label><input class="form-control" type="number" name="stock_quantity" value="0"></div><div class="col-md-3"><label class="form-label">Cảnh báo dưới</label><input class="form-control" type="number" name="minimum_stock" value="10"></div>
<input type="hidden" name="status" value="active"><div><button class="btn btn-primary">Lưu thuốc</button></div></form></details></div>
<div class="panel"><form class="toolbar"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Tên hoặc mã thuốc"><button class="btn btn-primary">Tìm</button></form><div class="table-responsive"><table class="table"><thead><tr><th>Thuốc</th><th>Hoạt chất</th><th>Giá bán</th><th>Tồn kho</th><th></th></tr></thead><tbody>
@foreach($items as $item)<tr><td><strong>{{ $item->name }}</strong><small class="d-block text-muted">{{ $item->medicine_code }} · {{ $item->strength }}</small></td><td>{{ $item->active_ingredient }}</td><td>{{ number_format($item->selling_price) }}đ/{{ $item->unit }}</td><td><strong class="{{ $item->stock_quantity <= $item->minimum_stock ? 'text-danger' : '' }}">{{ $item->stock_quantity }}</strong></td><td><details><summary class="btn btn-sm btn-soft">Cập nhật</summary><form method="post" action="{{ route('admin.medicines.update',$item) }}" class="mt-2" style="min-width:310px">@csrf @method('PUT')
<input type="hidden" name="medicine_code" value="{{ $item->medicine_code }}"><input type="hidden" name="active_ingredient" value="{{ $item->active_ingredient }}"><input type="hidden" name="dosage_form" value="{{ $item->dosage_form }}"><input type="hidden" name="strength" value="{{ $item->strength }}"><input type="hidden" name="unit" value="{{ $item->unit }}"><input type="hidden" name="manufacturer" value="{{ $item->manufacturer }}"><input type="hidden" name="usage_instruction" value="{{ $item->usage_instruction }}"><input type="hidden" name="contraindication" value="{{ $item->contraindication }}">
<label class="form-label">Tên thuốc</label><input class="form-control mb-2" name="name" value="{{ $item->name }}"><div class="row g-2"><div class="col"><label class="form-label">Giá nhập</label><input class="form-control" type="number" name="purchase_price" value="{{ $item->purchase_price }}"></div><div class="col"><label class="form-label">Giá bán</label><input class="form-control" type="number" name="selling_price" value="{{ $item->selling_price }}"></div></div><div class="row g-2 mt-1"><div class="col"><label class="form-label">Tồn kho</label><input class="form-control" type="number" name="stock_quantity" value="{{ $item->stock_quantity }}"></div><div class="col"><label class="form-label">Cảnh báo</label><input class="form-control" type="number" name="minimum_stock" value="{{ $item->minimum_stock }}"></div></div><select class="form-select my-2" name="status"><option value="active">Hoạt động</option><option value="inactive" @if($item->status==='inactive') selected @endif>Tạm ẩn</option></select><button class="btn btn-primary btn-sm">Lưu thay đổi</button></form></details></td></tr>@endforeach
</tbody></table></div>{{ $items->links() }}</div>
@endsection
