@extends('layouts.admin')
@section('title','Thống kê') @section('pageTitle','Thống kê & báo cáo')
@section('content')
<div class="panel mb-4"><form class="toolbar"><input class="form-control" type="date" name="from" value="{{ request('from') }}"><input class="form-control" type="date" name="to" value="{{ request('to') }}"><select class="form-select" name="specialty_id"><option value="">Mọi chuyên khoa</option>@foreach($specialtyOptions as $s)<option value="{{ $s->id }}" @if(request('specialty_id')==$s->id) selected @endif>{{ $s->name }}</option>@endforeach</select><select class="form-select" name="doctor_id"><option value="">Mọi bác sĩ</option>@foreach($doctorOptions as $d)<option value="{{ $d->id }}" @if(request('doctor_id')==$d->id) selected @endif>{{ $d->user->name }}</option>@endforeach</select><button class="btn btn-primary">Áp dụng</button></form></div>
<div class="row g-3 mb-4">@foreach([['Bệnh nhân',$patients],['Bác sĩ',$doctors],['Lịch trong kỳ',$appointments],['Doanh thu lọc',number_format($filteredRevenue).'đ']] as $stat)<div class="col-sm-6 col-xl-3"><div class="stat-card"><small>{{ $stat[0] }}</small><strong>{{ $stat[1] }}</strong></div></div>@endforeach</div>
<div class="row g-4 mb-4"><div class="col-lg-6"><div class="panel"><h2 class="h5 fw-bold">Lịch hẹn theo trạng thái</h2><canvas id="statusReport" height="130"></canvas></div></div><div class="col-lg-6"><div class="panel"><h2 class="h5 fw-bold">Doanh thu 12 tháng</h2><canvas id="revenueReport" height="130"></canvas></div></div></div>
<div class="row g-4"><div class="col-lg-4"><div class="panel h-100"><h2 class="h5 fw-bold">Top bác sĩ</h2>@foreach($topDoctors as $doctor)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $doctor->user->name }}</span><strong>{{ $doctor->completed_count }} lượt</strong></div>@endforeach</div></div><div class="col-lg-4"><div class="panel h-100"><h2 class="h5 fw-bold">Top thuốc được kê</h2>@forelse($topMedicines as $medicine)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $medicine->name }}</span><strong>{{ $medicine->total }}</strong></div>@empty<p class="text-muted">Chưa có dữ liệu.</p>@endforelse</div></div><div class="col-lg-4"><div class="panel h-100"><h2 class="h5 fw-bold">Công nợ</h2><small class="text-muted">Hóa đơn chưa thu đủ</small><strong class="d-block display-5 mt-2">{{ $unpaidInvoices }}</strong><hr><small class="text-muted">Doanh thu hôm nay</small><strong class="d-block mt-2">{{ number_format($todayRevenue) }}đ</strong></div></div></div>
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script><script>
new Chart(document.getElementById('statusReport'),{type:'doughnut',data:{labels:@json($statusChart->keys()),datasets:[{data:@json($statusChart->values()),backgroundColor:['#0f8b8d','#12304a','#f29d72','#72b5d8','#63b79c','#d95364','#a7bbc5']}]},options:{plugins:{legend:{position:'bottom'}}}});
new Chart(document.getElementById('revenueReport'),{type:'line',data:{labels:@json($revenueByMonth->keys()),datasets:[{data:@json($revenueByMonth->values()),borderColor:'#0f8b8d',backgroundColor:'rgba(15,139,141,.12)',fill:true,tension:.35}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true}}}});
</script>@endpush
@endsection
