@extends('layouts.admin')
@section('title','Dịch vụ') @section('pageTitle','Dịch vụ khám')
@section('content')
<div class="row g-4"><div class="col-lg-4"><div class="panel"><h2 class="h5 fw-bold">Thêm dịch vụ</h2>
<form method="post" action="{{ route('admin.services.store') }}">@csrf
<label class="form-label mt-2">Mã dịch vụ</label><input class="form-control" name="service_code" required><label class="form-label mt-3">Tên dịch vụ</label><input class="form-control" name="name" required>
<label class="form-label mt-3">Chuyên khoa</label><select class="form-select" name="specialty_id"><option value="">Dùng chung</option>@foreach($specialties as $s)<option value="{{ $s->id }}">{{ $s->name }}</option>@endforeach</select>
<label class="form-label mt-3">Giá</label><input class="form-control" type="number" name="price" min="0" required><label class="form-label mt-3">Mô tả</label><textarea class="form-control" name="description"></textarea><input type="hidden" name="status" value="active"><button class="btn btn-primary w-100 mt-4">Thêm dịch vụ</button>
</form></div></div><div class="col-lg-8"><div class="panel"><div class="table-responsive"><table class="table"><thead><tr><th>Mã</th><th>Dịch vụ</th><th>Chuyên khoa</th><th>Giá</th><th></th></tr></thead><tbody>
@foreach($items as $item)<tr><td>{{ $item->service_code }}</td><td><strong>{{ $item->name }}</strong><small class="d-block text-muted">{{ $item->status }}</small></td><td>{{ optional($item->specialty)->name ?: 'Dùng chung' }}</td><td>{{ number_format($item->price) }}đ</td><td><details><summary class="btn btn-sm btn-soft">Chỉnh sửa</summary><form method="post" action="{{ route('admin.services.update',$item) }}" class="mt-2" style="min-width:300px">@csrf @method('PUT')<input type="hidden" name="service_code" value="{{ $item->service_code }}"><input class="form-control mb-2" name="name" value="{{ $item->name }}"><select class="form-select mb-2" name="specialty_id"><option value="">Dùng chung</option>@foreach($specialties as $s)<option value="{{ $s->id }}" @if($item->specialty_id===$s->id) selected @endif>{{ $s->name }}</option>@endforeach</select><input class="form-control mb-2" type="number" name="price" value="{{ $item->price }}"><textarea class="form-control mb-2" name="description">{{ $item->description }}</textarea><select class="form-select mb-2" name="status"><option value="active">Hoạt động</option><option value="inactive" @if($item->status==='inactive') selected @endif>Tạm ẩn</option></select><button class="btn btn-primary btn-sm">Lưu thay đổi</button></form></details></td></tr>@endforeach
</tbody></table></div>{{ $items->links() }}</div></div></div>
@endsection
