@extends('layouts.receptionist')
@section('title',$invoice->invoice_code) @section('pageTitle','Chi tiết hóa đơn')
@section('content')
<div class="row g-4"><div class="col-lg-8"><div class="panel"><div class="d-flex justify-content-between"><div><span class="eyebrow">{{ $invoice->invoice_code }}</span><h2 class="h4 fw-bold">{{ $invoice->patient->full_name }}</h2></div><span class="badge-status {{ $invoice->payment_status }}">{{ $invoice->payment_status }}</span></div>
<div class="table-responsive mt-4"><table class="table"><thead><tr><th>Nội dung</th><th>SL</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->quantity }}</td><td>{{ number_format($item->unit_price) }}đ</td><td>{{ number_format($item->amount) }}đ</td></tr>@endforeach</tbody><tfoot><tr><td colspan="3">Tạm tính</td><td>{{ number_format($invoice->service_amount+$invoice->medicine_amount) }}đ</td></tr><tr><td colspan="3">Giảm giá</td><td>-{{ number_format($invoice->discount_amount) }}đ</td></tr><tr class="fs-5 fw-bold"><td colspan="3">Tổng cộng</td><td>{{ number_format($invoice->total_amount) }}đ</td></tr></tfoot></table></div>
<div class="d-flex gap-2"><a class="btn btn-soft" target="_blank" href="{{ route('receptionist.invoices.print',$invoice) }}"><i class="bi bi-printer"></i> In hóa đơn</a>@if($invoice->payment_status==='unpaid')<form method="post" action="{{ route('receptionist.invoices.cancel',$invoice) }}">@csrf<button class="btn btn-outline-danger" data-confirm="Hủy hóa đơn và hoàn lại toàn bộ thuốc vào kho?">Hủy hóa đơn</button></form>@endif</div>
</div></div><div class="col-lg-4"><div class="panel"><h2 class="h5 fw-bold">Ghi nhận thanh toán</h2><p class="text-muted">Còn lại <strong class="text-dark">{{ number_format($invoice->outstanding_amount) }}đ</strong></p>
@if(!in_array($invoice->payment_status,['paid','cancelled']))<form method="post" action="{{ route('receptionist.invoices.pay',$invoice) }}">@csrf<label class="form-label">Số tiền</label><input class="form-control mb-3" type="number" name="amount" max="{{ $invoice->outstanding_amount }}" value="{{ $invoice->outstanding_amount }}"><label class="form-label">Phương thức</label><select class="form-select mb-3" name="payment_method"><option value="cash">Tiền mặt</option><option value="bank_transfer">Chuyển khoản</option><option value="card">Thẻ</option></select><input class="form-control mb-3" name="transaction_reference" placeholder="Mã giao dịch (nếu có)"><button class="btn btn-primary w-100">Xác nhận thanh toán</button></form>@else<div class="alert {{ $invoice->payment_status==='paid' ? 'alert-success' : 'alert-secondary' }}">{{ $invoice->payment_status==='paid' ? 'Hóa đơn đã thanh toán đủ.' : 'Hóa đơn đã hủy.' }}</div>@endif
<hr><h3 class="h6 fw-bold">Lịch sử thu tiền</h3>@forelse($invoice->payments as $p)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $p->payment_date->format('d/m H:i') }}<small class="d-block text-muted">{{ $p->payment_method }}</small></span><strong>{{ number_format($p->amount) }}đ</strong></div>@empty<p class="text-muted">Chưa có giao dịch.</p>@endforelse
</div></div></div>
@endsection
